// Import all IPC modules
import './ipc/settings'
import './ipc/auth'
import './ipc/ai'
import './ipc/bills'
import './ipc/expenses'
import './ipc/data'
import './ipc/clients'
import './ipc/system'
import './ipc/email'
import './ipc/automation'
import './ipc/sync'